### PR TITLE
Feature: Version 4 (v12 support)

### LINKED ISSUE #1: TYPO3 v12 compatibility
Please consider to support TYPO3 v12. 🙏

### PR DESCRIPTION
**Pull request by maikschneider**
This version will support TYPO3 v12

* stop including content element wizard globally, add notice to readme
* refactor typoscript setup
* use Dependency Injection
* drop support for v9

fixes #1

### CODE REVIEW

**Comment by maikschneider** [comment]
ToDos:

- [ ] Event binding not working when modal closes and re-opens
- [ ] Change of active states not working (box or panel click)

**Comment by crediaHasselberg** [comment]
Hallo Herr Schneider,

gibt es zeitliche Pläne, wann der Support für TYPO3 12 angedacht ist?

Lieben Gruß
Daniel Hasselberg

**Comment by maikschneider** [comment]
Hi Daniel,
since I need a working v12 version for a new project, I'm pretty confident to release it in a few weeks.
Cheers!

**Comment by mdahms** [comment]
Hello Mr. Schneider,
Is there any new information yet? When will the update probably be ready?

**Pull request merged**
